spring.application.name=springboot1-9
server.port=8081

# Thymeleaf
spring.thymeleaf.cache=false

# Kết nối SQL Server (Sửa lại mật khẩu 123456 thành mật khẩu sa của bạn)
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS01;databaseName=webst9;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA & Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB